using Michaelhouse.Mobile.Models;
using Michaelhouse.Mobile.Services;
using ZXing.Net.Maui;
using ZXing.Net.Maui.Controls;
namespace Michaelhouse.Mobile.Pages;

internal static class MobileBindings
{
    public static View TextLabel(string path)
    {
        var label = new Label { Style = (Style)Application.Current!.Resources["CardLabel"] };
        label.SetBinding(Label.TextProperty, path);
        var card = new Border { Content = label, Stroke = Color.FromArgb("#EEEEEE"), StrokeThickness = 1, Padding = 0 };
        return card;
    }
}

public sealed class LoginPage : ContentPage { readonly Entry email=new(){Placeholder="Email"}; readonly Entry password=new(){Placeholder="Password",IsPassword=true}; readonly Label msg=new(){TextColor=Colors.Firebrick}; readonly MobileApiClient api; readonly SessionService session; public LoginPage(MobileApiClient a,SessionService s){api=a;session=s;Content=new VerticalStackLayout{Padding=28,Children={new Label{Text="Michaelhouse",Style=(Style)Application.Current!.Resources["Headline"]},email,password,new Button{Text="Sign in",Command=new Command(async()=>await Go())},msg}};} async Task Go(){try{msg.Text="Signing in…";var x=await api.PostAsync<LoginResponse>("auth/login",new{email=email.Text,password=password.Text});if(String.IsNullOrEmpty(x?.Token))throw new InvalidOperationException("The server did not return a login token.");await session.SaveAsync(x.Token);api.SetToken(x.Token);Page page=String.Equals(x.Role,"Teacher",StringComparison.OrdinalIgnoreCase)?new TeacherSessionsPage(api,session,x.Name):String.Equals(x.Role,"Driver",StringComparison.OrdinalIgnoreCase)?new DriverTripsPage(api,session,x.Name):String.Equals(x.Role,"HouseMaster",StringComparison.OrdinalIgnoreCase)?new HouseMasterHomePage(api,session,x.Name):String.Equals(x.Role,"Student",StringComparison.OrdinalIgnoreCase)?new DashboardPage(api,session,x.Name):throw new InvalidOperationException("This mobile portal is not available to this account.");await Navigation.PushAsync(page);Navigation.RemovePage(this);}catch(Exception ex){msg.Text=String.IsNullOrWhiteSpace(ex.Message)?"Sign-in failed.":ex.Message;}} }
public sealed class DashboardPage : ContentPage { public DashboardPage(MobileApiClient a,SessionService s,string n){Title="Michaelhouse";Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text="Welcome, "+n,Style=(Style)Application.Current!.Resources["Headline"],HorizontalTextAlignment=TextAlignment.Start},B("My profile",()=>Navigation.PushAsync(new StudentProfilePage(a))),B("Timetable",()=>Navigation.PushAsync(new StudentTimetablePage(a))),B("Results",()=>Navigation.PushAsync(new StudentResultsPage(a))),B("Attendance",()=>Navigation.PushAsync(new StudentAttendancePage(a))),B("Alerts",()=>Navigation.PushAsync(new StudentAlertsPage(a))),B("Emergency safety",()=>Navigation.PushAsync(new StudentEmergencyPage(a))),B("Sign out",async()=>{s.Clear();a.SetToken(null);await Navigation.PushAsync(new LoginPage(a,s));})}};} static Button B(string t,Func<Task> f)=>new(){Text=t,Command=new Command(async()=>await f())}; }

public sealed class StudentProfilePage : ContentPage { readonly MobileApiClient api; readonly Label detail=new(); public StudentProfilePage(MobileApiClient a){api=a;Title="My profile";Content=new VerticalStackLayout{Padding=20,Children={detail}};} protected override async void OnAppearing(){base.OnAppearing();try{var s=await api.GetAsync<StudentDto>("student/profile");detail.Text=s==null?"Profile unavailable.":$"{s.Name}\n{s.StudentNumber}\n{s.Grade}";}catch{detail.Text="Unable to load your profile.";}} }
public sealed class StudentTimetablePage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public StudentTimetablePage(MobileApiClient a){api=a;Title="Timetable";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Subject"));Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<TimetableSlotDto>>("student/timetable")??[];list.ItemsSource=x;state.Text=x.Count==0?"No timetable is available.":"";}catch{state.Text="Unable to load the timetable.";}} }
public sealed class StudentResultsPage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public StudentResultsPage(MobileApiClient a){api=a;Title="Results";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Subject"));Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<ResultDto>>("student/results")??[];list.ItemsSource=x;state.Text=x.Count==0?"Results are not yet available.":"";}catch{state.Text="Unable to load results.";}} }
public sealed class StudentAttendancePage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public StudentAttendancePage(MobileApiClient a){api=a;Title="Attendance";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Subject"));Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<AttendanceDto>("student/attendance");list.ItemsSource=x?.Records;state.Text=x==null||x.Records.Count==0?"No attendance records are available.":"";}catch{state.Text="Unable to load attendance.";}} }
public sealed class StudentAlertsPage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public StudentAlertsPage(MobileApiClient a){api=a;Title="Alerts";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Message"));Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<AlertDto>>("student/alerts")??[];list.ItemsSource=x;state.Text=x.Count==0?"You have no alerts.":"";}catch{state.Text="Unable to load alerts.";}} }
public sealed class StudentEmergencyPage : ContentPage { readonly MobileApiClient api; readonly Label state=new(){FontAttributes=FontAttributes.Bold}; EmergencyAlertDto? alert; readonly Button confirm; public StudentEmergencyPage(MobileApiClient a){api=a;Title="Emergency safety";confirm=new Button{Text="Confirm I am safe",IsEnabled=false,Command=new Command(async()=>await Confirm())};Content=new VerticalStackLayout{Padding=20,Spacing=14,Children={new Label{Text="Emergency safety",Style=(Style)Application.Current!.Resources["Headline"],HorizontalTextAlignment=TextAlignment.Start},state,confirm}};} protected override async void OnAppearing(){base.OnAppearing();try{alert=await api.GetAsync<EmergencyAlertDto>("student/emergency");if(alert==null){state.Text="All clear. There is no active emergency alert.";return;}state.Text=$"{alert.Message}\nAssembly point: {alert.AssemblyPoint}\nSafe zone: {alert.RadiusMeters:0}m";confirm.IsEnabled=true;}catch{state.Text="Unable to check emergency status.";}} async Task Confirm(){try{state.Text="Getting your GPS location…";confirm.IsEnabled=false;var permission=await Permissions.RequestAsync<Permissions.LocationWhenInUse>();if(permission!=PermissionStatus.Granted)throw new InvalidOperationException("Location permission is required to confirm safety.");var location=await Geolocation.Default.GetLocationAsync(new GeolocationRequest(GeolocationAccuracy.Best,TimeSpan.FromSeconds(20)));if(location==null)throw new InvalidOperationException("Current GPS location is unavailable.");var result=await api.PostAsync<EmergencyConfirmationDto>("student/emergency/confirm",new{latitude=location.Latitude,longitude=location.Longitude});state.Text=result?.Message??"Safety confirmation could not be completed.";state.TextColor=result?.WithinGeofence==true?Colors.DarkGreen:Colors.Firebrick;}catch(Exception ex){state.Text=ex.Message;state.TextColor=Colors.Firebrick;}finally{confirm.IsEnabled=true;}} }

public sealed class TeacherSessionsPage : ContentPage { readonly MobileApiClient api; readonly SessionService session; readonly CollectionView list=new(); readonly Label state=new(); public TeacherSessionsPage(MobileApiClient a,SessionService s,string name){api=a;session=s;Title="Attendance";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Subject"));list.SelectionChanged+=async(_,e)=>{if(e.CurrentSelection.FirstOrDefault()is TeacherSessionDto x)await Navigation.PushAsync(new TeacherRegisterPage(api,x));};Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text="My classes",Style=(Style)Application.Current!.Resources["Headline"],HorizontalTextAlignment=TextAlignment.Start},state,list,new Button{Text="Sign out",Command=new Command(async()=>{session.Clear();api.SetToken(null);await Navigation.PushAsync(new LoginPage(api,session));})}}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<TeacherSessionDto>>("teacher/sessions")??[];list.ItemsSource=x;state.Text=x.Count==0?"No assigned classes are available.":"";}catch{state.Text="Unable to load your classes.";}} }
public sealed class TeacherRegisterPage : ContentPage { readonly MobileApiClient api; readonly TeacherSessionDto session; readonly VerticalStackLayout rows=new(){Spacing=8}; readonly Label state=new(); readonly Dictionary<int,Picker> choices=new(); DateTime date; public TeacherRegisterPage(MobileApiClient a,TeacherSessionDto s){api=a;session=s;Title=s.Subject;Content=new ScrollView{Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text=$"{s.Subject} · Grade {s.Grade}",Style=(Style)Application.Current!.Resources["SubHeadline"],HorizontalTextAlignment=TextAlignment.Start},state,rows,new Button{Text="Save attendance",Command=new Command(async()=>await Save())}}}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<TeacherRegisterDto>($"teacher/sessions/{session.SubjectId}/attendance");if(x==null){state.Text="Register unavailable.";return;}date=x.Date;rows.Children.Clear();choices.Clear();foreach(var student in x.Students){var picker=new Picker{Title="Status",ItemsSource=new List<string>{"Present","Absent","Late"},SelectedItem=student.Status};choices[student.StudentId]=picker;rows.Children.Add(new Border{Padding=12,Content=new VerticalStackLayout{Children={new Label{Text=student.Name,FontAttributes=FontAttributes.Bold},picker}}});}}catch{state.Text="Unable to load the register.";}} async Task Save(){try{state.Text="Saving…";var students=choices.Select(x=>new{studentId=x.Key,status=x.Value.SelectedItem?.ToString()??"Present"});await api.PostAsync<object>($"teacher/sessions/{session.SubjectId}/attendance",new{date,students});state.Text="Attendance saved.";}catch(Exception ex){state.Text=String.IsNullOrWhiteSpace(ex.Message)?"Unable to save attendance.":ex.Message;}} }
public sealed class DriverTripsPage : ContentPage { readonly MobileApiClient api; readonly SessionService session; readonly CollectionView trips=new(); readonly Label state=new(); public DriverTripsPage(MobileApiClient a,SessionService s,string name){api=a;session=s;Title="My trips";trips.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Title"));trips.SelectionChanged+=async(_,e)=>{if(e.CurrentSelection.FirstOrDefault()is DriverTripDto x)await Navigation.PushAsync(new DriverManifestPage(api,x));};Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text="Assigned trips",Style=(Style)Application.Current!.Resources["Headline"],HorizontalTextAlignment=TextAlignment.Start},state,trips,new Button{Text="Sign out",Command=new Command(async()=>{session.Clear();api.SetToken(null);await Navigation.PushAsync(new LoginPage(api,session));})}}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<DriverTripDto>>("driver/trips")??[];trips.ItemsSource=x;state.Text=x.Count==0?"No active trips are assigned to you.":"";}catch{state.Text="Unable to load assigned trips.";}} }
public sealed class DriverManifestPage : ContentPage
{
    readonly MobileApiClient api;
    readonly DriverTripDto trip;
    readonly CollectionView students = new();
    readonly Label state = new();

    public DriverManifestPage(MobileApiClient a, DriverTripDto t)
    {
        api = a;
        trip = t;
        Title = t.Title;

        students.ItemTemplate = new DataTemplate(() => MobileBindings.TextLabel("Name"));

        Content = new VerticalStackLayout
        {
            Padding = 20,
            Spacing = 12,
            Children =
            {
                new Label
                {
                    Text = t.Title,
                    Style = (Style)Application.Current!.Resources["SubHeadline"],
                    HorizontalTextAlignment = TextAlignment.Start
                },
                state,
                students,
                new Button
                {
                    Text = "Scan boarding QR",
                    Command = new Command(async () => await Navigation.PushAsync(new DriverQrScanPage(api, trip, "before")))
                },
                new Button
                {
                    Text = "Scan return QR",
                    Command = new Command(async () => await Navigation.PushAsync(new DriverQrScanPage(api, trip, "after")))
                }
            }
        };
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();
        try
        {
            var x = await api.GetAsync<DriverManifestDto>($"driver/trips/{trip.Id}/manifest");
            students.ItemsSource = x?.Students;
            state.Text = x == null || x.Students.Count == 0 ? "No students are expected on this trip." : "";
        }
        catch
        {
            state.Text = "Unable to load trip manifest.";
        }
    }
}
public sealed class DriverQrScanPage : ContentPage { readonly MobileApiClient api; readonly DriverTripDto trip; readonly string phase; readonly Label result=new(){FontAttributes=FontAttributes.Bold}; bool scanning; public DriverQrScanPage(MobileApiClient a,DriverTripDto t,string p){api=a;trip=t;phase=p;Title=p=="before"?"Boarding scan":"Return scan";var camera=new CameraBarcodeReaderView{IsDetecting=true,Options=new BarcodeReaderOptions{Formats=BarcodeFormats.All}};camera.BarcodesDetected+=Detected;Content=new Grid{RowDefinitions={new RowDefinition{Height=GridLength.Star},new RowDefinition{Height=GridLength.Auto}},Children={camera,result}};Grid.SetRow(result,1);} void Detected(object? sender,BarcodeDetectionEventArgs e){var value=e.Results.FirstOrDefault()?.Value;if(scanning||String.IsNullOrWhiteSpace(value))return;scanning=true;MainThread.BeginInvokeOnMainThread(async()=>{try{var x=await api.PostAsync<DriverScanResultDto>($"driver/trips/{trip.Id}/scan",new{qrValue=value,phase});result.Text=x?.Message??"Scan could not be processed.";result.TextColor=x?.Success==true?Colors.DarkGreen:Colors.Firebrick;}catch(Exception ex){result.Text=ex.Message;result.TextColor=Colors.Firebrick;}finally{await Task.Delay(1200);scanning=false;}});} }
public sealed class HouseMasterHomePage : ContentPage { readonly MobileApiClient api; readonly SessionService session; public HouseMasterHomePage(MobileApiClient a,SessionService s,string name){api=a;session=s;Title="Residence emergency";Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text="Residence emergency",Style=(Style)Application.Current!.Resources["Headline"],HorizontalTextAlignment=TextAlignment.Start},new Button{Text="Emergency alerts",Command=new Command(async()=>await Navigation.PushAsync(new HouseMasterAlertsPage(api)))},new Button{Text="Emergency roll call",Command=new Command(async()=>await Navigation.PushAsync(new HouseMasterResidencesPage(api)))},new Button{Text="Sign out",Command=new Command(async()=>{session.Clear();api.SetToken(null);await Navigation.PushAsync(new LoginPage(api,session));})}}};} }
public sealed class HouseMasterAlertsPage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public HouseMasterAlertsPage(MobileApiClient a){api=a;Title="Emergency alerts";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Title"));Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<HouseMasterAlertDto>>("housemaster/alerts")??[];list.ItemsSource=x;state.Text=x.Count==0?"No active residence alerts.":"";}catch{state.Text="Unable to load emergency alerts.";}} }
public sealed class HouseMasterResidencesPage : ContentPage { readonly MobileApiClient api; readonly CollectionView list=new(); readonly Label state=new(); public HouseMasterResidencesPage(MobileApiClient a){api=a;Title="Emergency roll call";list.ItemTemplate=new DataTemplate(()=>MobileBindings.TextLabel("Name"));list.SelectionChanged+=async(_,e)=>{if(e.CurrentSelection.FirstOrDefault()is HouseMasterResidenceDto x)await Navigation.PushAsync(new EmergencyRollCallPage(api,x));};Content=new VerticalStackLayout{Padding=20,Children={state,list}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<HouseMasterResidenceDto>>("housemaster/residences")??[];list.ItemsSource=x;state.Text=x.Count==0?"No residence is assigned to you.":"";}catch{state.Text="Unable to load your residences.";}} }
public sealed class EmergencyRollCallPage : ContentPage { readonly MobileApiClient api; readonly HouseMasterResidenceDto residence; readonly VerticalStackLayout rows=new(){Spacing=8}; readonly Label state=new(); public EmergencyRollCallPage(MobileApiClient a,HouseMasterResidenceDto r){api=a;residence=r;Title="Emergency roll call";Content=new ScrollView{Content=new VerticalStackLayout{Padding=20,Spacing=12,Children={new Label{Text=r.Name,Style=(Style)Application.Current!.Resources["SubHeadline"],HorizontalTextAlignment=TextAlignment.Start},state,rows}}};} protected override async void OnAppearing(){base.OnAppearing();try{var x=await api.GetAsync<List<RollCallStudentDto>>($"housemaster/residences/{residence.Id}/rollcall")??[];rows.Children.Clear();foreach(var student in x)rows.Children.Add(new Button{Text="Mark present · "+student.Name,Command=new Command(async()=>await Mark(student))});state.Text=x.Count==0?"No active students are listed.":"";}catch{state.Text="Unable to load the emergency roll call.";}} async Task Mark(RollCallStudentDto student){try{await api.PostAsync<object>($"housemaster/residences/{residence.Id}/rollcall/{student.StudentId}",null);state.Text=student.Name+" marked present.";}catch(Exception ex){state.Text=ex.Message;}} }
