// <auto-generated />
namespace Michaelhouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Migrations/202604060106579_InitialCreate.Designer.cs
            get { return "202604060106579_InitialCreate"; }
========
            get { return "202604061518172_InitialCreate"; }
>>>>>>>> 2bf4587a5288f74c868b5776aa3f45b521c3e24c:Migrations/202604061518172_InitialCreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
