// <auto-generated />
namespace Michaelhouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initialcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Migrations/202605071035543_InitialCreate.Designer.cs
            get { return "202605071035543_InitialCreate"; }
========
            get { return "202605071006223_initialcreate"; }
>>>>>>>> 3748cc8bd719a62d206a321fa467f45462478c19:Migrations/202605071006223_initialcreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
