// <auto-generated />
namespace Michaelhouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Migrations/202604042251374_InitialCreate.Designer.cs
            get { return "202604042251374_InitialCreate"; }
========
            get { return "202604022244477_InitialCreate"; }
>>>>>>>> fd5ded9f696e1d78c5a52b31a453ae61bc131b0f:Migrations/202604022244477_InitialCreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
