// <auto-generated />
namespace Michaelhouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UseDateTime2ForTripRequests1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UseDateTime2ForTripRequests1));
        
        string IMigrationMetadata.Id
        {
            get { return "202605061916195_UseDateTime2ForTripRequests1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
