// <auto-generated />
namespace Michaelhouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_UserId_To_DriverApplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UserId_To_DriverApplication));
        
        string IMigrationMetadata.Id
        {
            get { return "202604261123019_Add_UserId_To_DriverApplication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
